// src/config/swaggerConfig.ts
import swaggerAutogen from 'swagger-autogen';

const doc = {
  info: {
    title: 'Biofuel Management System API',
    description: 'Express API for Biofuel Management System with autogenerated Swagger docs',
    version: '1.0.0',
    contact: {
      name: 'API Support',
      email: 'support@biofuel-system.com',
    },
  },
  host: 'localhost:3000',
  schemes: ['http'],
  securityDefinitions: {
    bearerAuth: {
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
      description: 'Bearer token for authentication',
    },
  },
  definitions: {
    // Plant definitions
    Plant: {
      _id: '507f1f77bcf86cd799439011',
      name: 'Main Plant',
      code: 'PLANT001',
      location: 'Mumbai',
      address: '123 Industrial Area, Mumbai',
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
    // Vehicle definitions
    Vehicle: {
      _id: '507f1f77bcf86cd799439012',
      vehicleNumber: 'MH12AB1234',
      vehicleType: 'buy',
      capacity: 10000,
      driverName: 'John Doe',
      driverPhone: '9876543210',
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
    // Vendor definitions
    Vendor: {
      _id: '507f1f77bcf86cd799439013',
      name: 'ABC Suppliers',
      code: 'VENDOR001',
      contactPerson: 'Jane Smith',
      phone: '9876543210',
      email: 'jane@abcsuppliers.com',
      address: '456 Business Park, Delhi',
      gstNumber: '27ABCDE1234F1Z5',
      linkedPlants: ['507f1f77bcf86cd799439011'],
      isActive: true,
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
    // User definitions
    User: {
      _id: '507f1f77bcf86cd799439014',
      username: 'admin',
      name: 'Admin User',
      empId: 'EMP001',
      role: 'admin',
      isActive: true,
      plantId: '507f1f77bcf86cd799439011',
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
  },
};

const outputFile = './docs/swagger-output.json';
const endpointsFiles = ['./src/app.ts'];

swaggerAutogen()(outputFile, endpointsFiles, doc);
