name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node (if needed for builds)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Configure AWS credentials (instead of apt-get awscli)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Install EB CLI
      - name: Install EB CLI
        run: pip install awsebcli --upgrade

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init weighingapp-backend --region ap-south-1 --platform docker
          eb use weighingapp-backend-env
          eb deploy
