name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install EB CLI
        run: pip install awsebcli --upgrade

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init weighingapp-backend --platform "Docker running on 64bit Amazon Linux 2" --region ap-south-1
          eb use weighingapp-backend-env
          eb deploy
